#!/usr/bin/perl

while (<*.mp3>)
{
    $old = $_;
    $old =~ s/\.mp3$//;
    $new = fix_name($old) . ".mp3";
    if ($new ne $_)
    {
        print" rename ($_) to ($new)\n";
        rename $_, $new;
    }
}

system("id3v2 -s *.mp3");
system("id3v2 -2 --TPOS=\"\" *.mp3");
system("chmod 644 *");
#system("eyeD3 --remove-images *.mp3");
#system("mv Folder.jpg cover.jpg");

sub fix_name
{
    my $name = shift;

    $name =~ s/^\(Disc .\) //g;
    $name =~ s/^([0-9][0-9]) - /\1 /g;
    $name =~ s/&/and/g;
    $name =~ s/[\(\)\[\]\{\}\.\,\'\?\/\\:"!]//g;
    $name =~ s/#/Number /g;
    $name =~ s/ +/ /g;
    $name =~ s/ /_/g;

    return $name;
}
