#!/usr/bin/perl

use MP3::Info;
use MP3::Tag;
use Getopt::Std;

$tn = 1;

print "Enter album title: ";
chomp ($album = <STDIN>);

print "Enter artist: ";
chomp ($artist = <STDIN>);

print "Enter artist sort: ";
chomp ($tsop = <STDIN>);

while (<*.mp3>)
{
	system "chmod 644 '$_'";
	#system "eyeD3 --remove-images '$_' >/dev/null";
    system "id3v2 -s '$_'";
    system "id3v2 -2 -T $tn '$_'";
    system "id3v2 -2 --TPOS=\"\" '$_'";
	system "id3v2 -2 -A \"$album\" '$_'";
	system "id3v2 -2 -a \"$artist\" '$_'";
	system "SetTSOP \"$tsop\" '$_'" if $tsop ne "";
	$tn++;

    my $tag = get_mp3tag($_);
    if ($tag)
    {
        my $title = $tag->{TITLE};
        my $tracknum = $tag->{TRACKNUM};
        my $newname = sprintf("%02d_%s.mp3", $tracknum, fix_name($title));
        print "rename $_ to $newname\n";
		rename($_, $newname);
    }
}

sub fix_name
{
    my $name = shift;

    $name =~ s/&/and/g;
    $name =~ s/[\(\)\[\]\{\}\,\'\.\?\/\\:"!<>]//g;
    $name =~ s/#/Number/g;
    $name =~ s/ +/ /g;
    $name =~ s/ $//g;
    $name =~ s/ /_/g;

    return $name;
}
