#!/usr/bin/perl

use strict;
use MP3::Tag;

my ($file, $mp3, $v2);

while ($#ARGV >= 0)
{
    $file = shift;
    $mp3 = MP3::Tag->new($file);
    $mp3->get_tags();
    $v2 = $mp3->{ID3v2};
    my ($extsop, undef) = $v2->get_frame("TCMP");
    print "$file: ";
    if (defined $extsop)
    {
	print "TCMP was $extsop, changing to 1\n";
        $v2->change_frame("TCMP", "1");
    }
    else
    {
	print "adding TCMP as 1\n";
        $v2->add_frame("TCMP", "1");
    }
    $v2->write_tag();
    $mp3->close();
}
