#!/usr/bin/perl

use strict;
use MP3::Tag;

my ($file, $mp3, $v2);

my $tsop = shift;

while ($#ARGV >= 0)
{
    $file = shift;
    $mp3 = MP3::Tag->new($file);
    $mp3->get_tags();
    $v2 = $mp3->{ID3v2};
    my ($extsop, undef) = $v2->get_frame("TSOP");
    print "$file: ";
    if (defined $extsop)
    {
	print "TSOP was $extsop, changing to $tsop\n";
        $v2->change_frame("TSOP", $tsop);
    }
    else
    {
	print "adding TSOP as $tsop\n";
        $v2->add_frame("TSOP", $tsop);
    }
    $v2->write_tag();
    $mp3->close();
}
