#!/usr/bin/perl

use strict;
use MP3::Tag;

my ($file, $mp3, $v2);

my $tsoa = shift;

while ($#ARGV >= 0)
{
    $file = shift;
    $mp3 = MP3::Tag->new($file);
    $mp3->get_tags();
    $v2 = $mp3->{ID3v2};
    my ($extsoa, undef) = $v2->get_frame("TSOA");
    print "$file: ";
    if (defined $extsoa)
    {
	print "TSOA was $extsoa, changing to $tsoa\n";
        $v2->change_frame("TSOA", $tsoa);
    }
    else
    {
	print "adding TSOA as $tsoa\n";
        $v2->add_frame("TSOA", $tsoa);
    }
    $v2->write_tag();
    $mp3->close();
}
